config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'artist_events/:id' => "search#artist_events", as: "artist_events"
  get 'venue_events/:id' => "search#venue_events", as: "venue_events"
  get 'local_events' => "search#local_events", as: "local_events"
  get 'results' => "search#results", as: 'results'

  resources :events do 
    resources :group_messages
    resources :direct_messages
  end
  resources :user_events

  get 'user_history/:sender_id/:recipient_id' => "direct_messages#user_history", as: 'user_history'

  get 'event_dm/:event_id/:sender_id/:recipient_id' => "direct_messages#event_dm", as: 'event_dm'
  
  post 'event_dm/:event_id/:sender_id/:recipient_id' => "direct_messages#create"

  get 'my_chats/:id' => "direct_messages#my_chats", as: 'my_chats'

  get 'my_events/:id' => "user_events#my_events", as: 'my_events'

  get 'event/:id/users' => "events#event_users", as: "event_users"

  post 'attend/:id' => "user_events#attend", as: "attend"
  post 'unattend/:id' => "user_events#unattend", as: "unattend"
  
  root 'search#index'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  require "search"
  # use 'Rails.cache.clear' to clear cache
  def index
    @user = User.find(current_user.id) if user_signed_in? 

  end

  def results
    if params[:q_name].present?
      @name = params[:q_name]
      # @name_results = Rails.cache.fetch(:name_results, expires_in: 24.hours) do
      #   ::Search.new.search_by_name(@name)
      # end
      @name_results = ::Search.new.search_by_name(@name)

      @artist_results = @name_results[0]
      @venue_results = @name_results[1]

    elsif params[:q_zip_code].present?

      @zip_code = params[:q_zip_code] 
      if !@zip_code.present?
        flash[:message] = "Please type SOMETHING before you hit search."

      elsif valid_zip?(@zip_code)

        # @zip_results = Rails.cache.fetch(:zip_results, expires_in: 24.hours) do
        #  ::Search.new.search_by_zip(@zip_code)
        # end
        @zip_results = ::Search.new.search_by_zip(@zip_code)

        @venue_results = @zip_results[0]
        @event_results = @zip_results[1]

        @artist_names = []
        @event_results.each do |a|
          artists = []
          a[:event_artists].each do |n|
            artists << n['Name']
          end
          @artist_names << artists
        end

      else
        flash[:message] = "Please enter a 5-digit number if you want to search by ZIP Code!"
        redirect_to root_path
      end

    end
  end


  def artist_events
    @artist_id = params[:id]
    # @artist_events = Rails.cache.fetch(:artist_events, expires_in: 24.hours) do
    #   ::Search.new.get_artist_events_by_id(@artist_id)
    # end

    @artist_events = ::Search.new.get_artist_events_by_id(@artist_id)

    # @artist_name = Rails.cache.fetch(:artist_name, expires_in: 24.hours) do
    #   ::Search.new.get_artist_name_by_id(@artist_id)
    # end
    @artist_name = ::Search.new.get_artist_name_by_id(@artist_id)

    @artist_names = []

    @page_header = @artist_name
    if @artist_events.present?
      @artist_events.each do |a|
        artists = []
        a[:event_artists].each do |n|
          artists << n['Name']
        end
        @artist_names << artists
      end

    else
      @message = "No Upcoming Events for this Artist"
    end

  end

  def venue_events
    @venue_id = params[:id]
    # @venue_events = Rails.cache.fetch(:venue_events, expires_in: 24.hours) do
    #   ::Search.new.get_venue_events_by_id(@venue_id)
    # end
    @venue_events = ::Search.new.get_venue_events_by_id(@venue_id)
    @artist_names = []
    
    if @venue_events.present?
      # To avoid another API call
      @venue_name = @venue_events.first[:event_venue]['Name']
      @page_header = @venue_name

      @venue_events.each do |a|
        artists = []
        a[:event_artists].each do |n|
          artists << n['Name']
        end
        @artist_names << artists
      end

    else
      @message = "No Upcoming Events at this Venue!"
      # @page_header = Rails.cache.fetch(:page_header, expires_in: 24.hours) do
      #   ::Search.new.get_venue_name_by_id(@venue_id)
      # end
      @page_header = ::Search.new.get_venue_name_by_id(@venue_id)
    end


  end

  def local_events
  end

  private

  def valid_zip?(zip)
    zip.length == 5
  end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/artist_events.html.erb
<h3>Upcoming Events:</h3>

<% @artist_events.each_with_index do |e, i| %>
  
  <div class="row">
    <div class="small-12 columns">
      <%= link_to("#{@artist_names[i].join('_')} @ #{e[:event_venue]['Name']} on #{DateTime.parse(e[:event_date]).strftime('%-m/%-d/%y')}", event_path(e[:jb_event_id]), method: :get, class: "large button expanded custom2") %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">    
      <%= link_to("Buy Tickets", "#{e[:event_url]}", method: :get, class: "large button expanded custom") %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">  
      <%= link_to("See Upcoming Events from #{e[:event_venue]['Name']}", venue_events_path(e[:event_venue]['Id']), method: :get, class: "large button expanded custom")  %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns custom button expanded">
      Find Shows by Artist:
    </div>
  </div>

  <% e[:event_artists].each do |a| %>
    <div class="row">
      <div class="small-12 columns"> 
        <%= link_to("Shows for #{a['Name']}", artist_events_path(a['Id']), methood: :get, class: "button large reverse expanded") %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/search/index.html.erb
<div class="row">
  <div class="small-12 columns expanded button custom2">
    <h2>
      <% if current_user.sign_in_count > 1 %>
        Welcome Back, <%= current_user.name.split(" ").first %>!
      <% else %>
        Welcome, <%= current_user.name.split(" ").first %>!
      <% end %>
    </h2>
  </div>
</div>

<div class="search_form background_wrapper_1">
  <%= form_tag("/results", method: "get") do %>
    <%= submit_tag("Search Artists and Venues by NAME", class: "button reverse expanded") %>
    <%= text_field_tag(:q_name) %>
  <% end %>
  <br>
  <br>
  <br>
</div>

<!-- <div class="background_parallax"></div> -->

<div class="search_form background_wrapper_2">
  <%= form_tag("/results", method: "get") do %>
    <%= submit_tag("Search Events and Venues by ZIP", class: "button reverse expanded") %>
    <%= text_field_tag(:q_zip_code) %>
  <% end %>
  <br>
  <br>
  <br>
</div>

<!-- <div class="background_parallax_2"></div> -->

<div class="background_wrapper_3">

  <div class="row">
    <div class="small-12 column app_info">
      <h2>Learn More</h2>
    </div>

    <div class= "small-12 columnp app_info_p">
      <p>Have you been too shy to go to a concert alone?  Well now you don't have to be!</p>

      <p>With Show Up &trade; you can meet before the show!</p>

      <p>It's very simple. Search for your favorite artists or venues, and then click "I'm Going." After that, you can find other people going and message them.  Or you can message the whole group of people going.</p>

      <p>Never go to a concert alone again!</p>
    </div>
  </div>

</div>

app/views/search/results.html.erb
<% if @artist_results.present? %>

  <div class="row">
    <div class="small-12 column expanded button custom2">
      <h2>Artists:</h2>
    </div>
  </div>

  <% @artist_results.each do |a| %>
    <div class="row">
      <div class="small-12 column expanded large button custom">
        <%= link_to(a[:artist_name], artist_events_path(a[:jb_artist_id]), method: :get) %>
      </div>
    </div>
  <% end %>

<% end %>

<br>
<!-- Display Venue Results -->
<% if @venue_results.present? %>

  <div class="row">
    <div class="small-12 column expanded button custom2">
      <h2>Venues:</h2>
    </div>
  </div>

  <% @venue_results.each do |v| %>
    <div class="row">
      <div class="small-12 column expanded large button custom">
        <%= link_to(v[:venue_name], venue_events_path(v[:jb_venue_id]), method: :get) %>
      </div>
    </div>
  <% end %>

<% end %>

<!-- Display Events Results -->
<% if @event_results.present? %>

  <div class="row">
    <div class="small-12 column expanded button custom2">
      <h2>Evnts:</h2>
    </div>
  </div>

  <% @event_results.each do |e| %>
    <div class="row">
      <div class="small-12 column expanded large button custom">
        <%= link_to("#{@artist_names} @ #{e[:event_venue]['Name']} on #{DateTime.parse(e[:event_date]).strftime('%-m/%-d%y')}", event_path(e[:jb_event_id]), method: :get) %>

      </div>
    </div>

   <div class="row">
      <div class="small-12 column expanded button custom"> 
        <%= link_to("Venue Website", venue_events_path(e[:event_venue]['Id']), method: :get)  %> 
      </div>
    </div>

    <div class="row">
      <div class="small-12 column expanded button custom"> 
        Artists:
      </div>
    </div>
          
    <% e[:event_artists].each do |a| %>
      <div class="row">
        <div class="small-12 column expanded button custom">
          <%= link_to(a['Name'], artist_events_path(a['Id']), methood: :get) %>
        </div>
      </div>
    <% end %>   

    <div class="row">
      <div class="small-12 column expanded button custom">
        <%= link_to("Buy Tickets", "#{e[:event_url]}") %>
      </div>
    </div>

    <hr>
  <% end %>

<% end %>

app/views/search/venue_events.html.erb
<h2>Upcoming Events:</h2>

<% @venue_events.each_with_index do |e, i| %>
  
  <div class="row">
    <div class="small-12 columns">
      <%= link_to("#{@artist_names[i].join(', ')} @ #{e[:event_venue]['Name']} on #{DateTime.parse(e[:event_date]).strftime('%-m/%-d/%y')}", event_path(e[:jb_event_id]), method: :get, class: "large button expanded custom2") %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">    
      <%= link_to("Buy Tickets", "#{e[:event_url]}", method: :get, class: "large button expanded custom") %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns large reverse2 button expanded">    
      Find Shows by Artist:
    </div>
  </div>

  <% e[:event_artists].each do |a| %>
    <div class="row">
      <div class="small-12 columns"> 
        <%= link_to("Shows for #{a['Name']}", artist_events_path(a['Id']), methood: :get, class: "button large reverse expanded") %>
      </div>
    </div>
  <% end %>

  <hr>

<% end %>