config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'artist_events/:id' => "search#artist_events", as: "artist_events"
  get 'venue_events/:id' => "search#venue_events", as: "venue_events"
  get 'local_events' => "search#local_events", as: "local_events"
  get 'results' => "search#results", as: 'results'

  resources :events do 
    resources :group_messages
    resources :direct_messages
  end
  resources :user_events

  get 'user_history/:sender_id/:recipient_id' => "direct_messages#user_history", as: 'user_history'

  get 'event_dm/:event_id/:sender_id/:recipient_id' => "direct_messages#event_dm", as: 'event_dm'
  
  post 'event_dm/:event_id/:sender_id/:recipient_id' => "direct_messages#create"

  get 'my_chats/:id' => "direct_messages#my_chats", as: 'my_chats'

  get 'my_events/:id' => "user_events#my_events", as: 'my_events'

  get 'event/:id/users' => "events#event_users", as: "event_users"

  post 'attend/:id' => "user_events#attend", as: "attend"
  post 'unattend/:id' => "user_events#unattend", as: "unattend"
  
  root 'search#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_one :group_message
  has_many :user_events
  has_many :users, through: :user_events

  # This needs to changes

  def user_attending?(user)
    Event.where(jb_event_id: self.jb_event_id, user_id: user.id).present? ? true : false
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_user, only: [:show]

  require "search"

  # before_action :set_event, only: [:attend, :unattend]

  def index
    # Should be list of all events which at least one person is going to...
    @events = Event.pluck(:jb_event_id).uniq
  end

  def show
    # @event_info = Rails.cache.fetch(:event_info, expires_in: 24.hours) do
    #   ::Search.new.get_event_by_id(params[:id])
    # end
    
    @event = Event.find_or_create_by(jb_event_id: params[:id])
    
    @event_info = ::Search.new.get_event_by_id(params[:id])

    @jb_event_id = @event_info[:jb_event_id]

    @event_date = @event_info[:event_date]
    @event_venue = @event_info[:event_venue]
    @event_artists = @event_info[:event_artists]
    @event_url = @event_info[:event_url]

    @artist_names = []
    # @artist_ids = []
    @event_artists.each do |a|
      @artist_names << a['Name']
      # @artist_ids << a['Id']
    end

    @marquee = "#{@artist_names.join(", ")} @ #{@event_venue['Name']} on #{DateTime.parse(@event_date).strftime("%-m/%-d/%y")}"
 
     @user_event = UserEvent.find_or_create_by(user_id: @user.id, event_id: @event.id) 

     @user_event.attending == true ? @user_going = true : @user_going = false

     @url = "https://www.google.com/maps/dir/Current+Location/#{@event_venue['Address']} #{@event_venue['City']} #{@event_venue['StateCode']} #{@event_venue['ZipCode']}"

     @url.gsub!(' ', '+').gsub!('++','+')

    # Ask orlando about this. 
    # There might be a way to use "build" so that the link can exist without creating the record
  end

  def event_users
    @page_header = "Who's Going"
    @event = Event.find(params[:id])
    @users = @event.users
    
    @event_users = []
    @users.each do |u|
      @event_users << u if UserEvent.find_by(event_id: @event.id, user_id: u.id, attending: true).present?
    end

    @jb_event_id = @event.jb_event_id 

    @event_info = ::Search.new.get_event_by_id(@jb_event_id)


    @event_date = @event_info[:event_date]
    @event_venue = @event_info[:event_venue]
    @event_artists = @event_info[:event_artists]
    @event_url = @event_info[:event_url]

    @artist_names = []
    # @artist_ids = []
    @event_artists.each do |a|
      @artist_names << a['Name']
      # @artist_ids << a['Id']
    end

    @marquee = "<strong>#{@artist_names.join(", ")}</strong><br><strong>#{@event_venue['Name']}</strong><br><strong>#{DateTime.parse(@event_date).strftime("%-m/%-d/%y")}</strong>"
  end

  def new
    # Not needed because of find_or_create_by method in show
  end

  def create
    # Not needed
  end

  def edit
    # Not needed
  end

  def update
    # Not needed
  end

  def destroy
    # Not needed
  end

  private

  def event_params
    parms.require(:event).permit(:jb_event_id)
  end

  def set_user
    @user = User.find(current_user.id)
  end

  # def set_event
  #   @event = Event.find(params[:id])
  # end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/event_users.html.erb
<h2 class="marquee"><%= @marquee.html_safe %></h2>

<% if %>
  <% @event_users.each do |u| %>
    <div class="row">
      <div class="small-12 columns custom2">
        <%= image_tag u.image, class: "users_image" %> <span class="users_name"><%= u.name %> <%= link_to("Send #{u.name.split(' ').first} a Message!", event_dm_path(@event.id, current_user.id, u.id), method: :get, class: "button custom") if current_user.id != u.id %></span>
      </div>
    </div>
  <% end %>

<% else %>
  <div class="row">
    <div class="small-12 columns">
      You arn't supposed to be here...
    </div>
  </div>
<% end %>

app/views/events/show.html.erb
<div class="row">
  <div class="small-12 column expanded button custom2">
    <h2><%= @marquee.html_safe %></h2>
  </div>
</div>

<div class="row">
  <div class="small-12 column expanded button custom">
    <% if @user_going %>
      <%= link_to("Already planning to go...", user_event_path(@user_event.id), method: :get, class: "button expanded custom") %>
    <% else %>
      <%= link_to("I want to go to this!!!", attend_path(@user_event.id), method: :post, class: "button expanded custom") %>
    <% end %>
  </div>
</div>

<br>

<% if @event_artists.length > 1 %>
  <div class="row">
    <div class="small-12 column expanded button custom2">
      <h2>Artists:</h2>
    </div>
  </div>
    <!-- Start doing things from here... -->
  <% @event_artists.each do |a| %>
    <div>
      <div class="small-12 expanded button custom">
        <%= a['Name'] %>
      </div>
    </div>
  <% end %>
<br>
<% end %>

<div class="row">
  <div class="small-12 column expanded button custom2">
    <h2>Venue:</h2> 
  </div>
</div>

<div class="row">
  <div class="small-12 expanded button custom">
    <%= @event_venue['Name'] %> <%= link_to("(Venue Website)", @event_venue['Url'], method: :get) %>
  </div>
</div>


<div class="row">
  <div class="small-12 expanded button custom">
    <%= @event_venue['Address'] %><br><%= @event_venue['City'] %>, <%= @event_venue['StateCode'] %> <%= @event_venue['ZipCode'] %>

    <%= link_to(image_tag("/assets/maps_icon.png", class: "gmaps"), @url.html_safe, method: :get) %>
  </div>
</div>


<div class="row">
  <div class="small-12 expanded button custom">
    <%= link_to("Buy Tickets!", @event_url, method: :get) %>
  </div>
</div>

<hr>