config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'artist_events/:id' => "search#artist_events", as: "artist_events"
  get 'venue_events/:id' => "search#venue_events", as: "venue_events"
  get 'local_events' => "search#local_events", as: "local_events"
  get 'results' => "search#results", as: 'results'

  resources :events do 
    resources :group_messages
    resources :direct_messages
  end
  resources :user_events

  get 'user_history/:sender_id/:recipient_id' => "direct_messages#user_history", as: 'user_history'

  get 'event_dm/:event_id/:sender_id/:recipient_id' => "direct_messages#event_dm", as: 'event_dm'
  
  post 'event_dm/:event_id/:sender_id/:recipient_id' => "direct_messages#create"

  get 'my_chats/:id' => "direct_messages#my_chats", as: 'my_chats'

  get 'my_events/:id' => "user_events#my_events", as: 'my_events'

  get 'event/:id/users' => "events#event_users", as: "event_users"

  post 'attend/:id' => "user_events#attend", as: "attend"
  post 'unattend/:id' => "user_events#unattend", as: "unattend"
  
  root 'search#index'

end

app/models/user_event.rb
class UserEvent < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/controllers/user_events_controller.rb
class UserEventsController < ApplicationController
  before_action :set_user, only: [:index, :show, :create, :destroy]

  before_action :set_event, only: [:show, :create, :destroy]

  require "search"

  def my_events
    @user_events = UserEvent.where(user_id: @user_id)
  end

  # my_events page
  def index
    @page_header = "My Events"
    @user_events = UserEvent.where(user_id: @user.id, attending: true )
    # don't know if i will actually use this
    @jb_event_ids = []
    @user_events.each do |ue|
      @jb_event_ids << Event.find(ue.event_id).jb_event_id
    end

    @jb_events = []
    @jb_event_ids.each do |j|
      @jb_events << ::Search.new.get_event_by_id(j)
    end

    @artist_names = []
    @jb_events.each do |a|
      if a[:event_artists].present?
        artists = []
        a[:event_artists].each do |n|
          artists << n['Name']
        end
      else
        artists = [""]
      end
      @artist_names << artists
    end

  end

  def show
    @page_header = "You're Seeing:"
    @user_event = UserEvent.find_by(event_id: @event.id, user_id: @user.id)

    # @user_event.update(attending: true)

    @all_users = UserEvent.where(event_id: @event.id)

    @event_info = ::Search.new.get_event_by_id(@event.jb_event_id)

    @jb_event_id = @event_info[:jb_event_id]

    @event_date = @event_info[:event_date]
    @event_venue = @event_info[:event_venue]
    @event_artists = @event_info[:event_artists]
    @event_url = @event_info[:event_url]

    @artist_names = []
    # @artist_ids = []
    @event_artists.each do |a|
      @artist_names << a['Name']
      # @artist_ids << a['Id']
    end

    @marquee = "<strong>#{@artist_names.join(", ")}</strong><br><strong>#{@event_venue['Name']}</strong><br><strong>#{DateTime.parse(@event_date).strftime("%-m/%-d/%y")}</strong>"

    @group_message = GroupMessage.where(event_id: @event.id, user_id: @user.id)

    @user_event.attending == true ? @user_going = true : @user_going = false

    @url = "https://www.google.com/maps/dir/Current+Location/#{@event_venue['Address']} #{@event_venue['City']} #{@event_venue['StateCode']} #{@event_venue['ZipCode']}"

    @url.gsub!(' ', '+').gsub!('++','+')

  end

  def new
    # Don't think I will need
  end

  def create
    @user_event = UserEvent.new(event_id: @event.id, user_id: @user.id)

    @user_event.save

    if @user_event.save
      # flash[:message] = "You are now attending this event!"
      
      # respond_to do |format|
      #   format.js
      # end    

      redirect_to event_path(@event.id)

      
    else
      flash[:message] = "There was a problem..."
      redirect_to event_path(@event.id)
    end
  end

  def destroy
    @user_event = UserEvent.find(params[:id])

    @user_event.destroy

    redirect_to root_path
  end

  def attend
    @user_event = UserEvent.find(params[:id])
    @user_event.update(attending: true)
    redirect_to user_event_path(@user_event.id)

  end

  def unattend
    @user_event = UserEvent.find(params[:id])
    @user_event.update(attending: false)
    redirect_to event_path(@user_event.event.jb_event_id)
  end

  private

  def event_params
    parms.require(:event).permit(:user_id, :event_id, :attending)
  end

  def set_user
    @user = User.find(current_user.id)
  end

  def set_event
    @event = UserEvent.find(params[:id]).event
  end

end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/views/user_events/create.js.erb
$(".attend_button_container").append('<%= link_to("Unattend", user_event_path(@event.id), method: :delete, class: "large button unattend", remote: true) %>')


$(".attend").on("ajax:complete", function(e){
  $(".attend").hide()
})

app/views/user_events/destroy.js.erb
$(".attend_button_container").append('<%= link_to("Attend", new_user_event_path(@event.id), method: :get, class: "large button attend", remote: true) %>')


$(".unattend").on("ajax:complete", function(e){
  $(".unattend").hide()
})

app/views/user_events/index.html.erb
<% if @jb_events.blank? || @jb_events[0][:jb_event_id] != 0 %>

    <% @jb_events.each_with_index do |j, i| %>

      <% unless j[:jb_event_id][0].nil? %>
        
        <a href="<%= event_path(j[:jb_event_id]) %>" class="large button custom2 expanded">
          <div class="row event_info">
            <div class="small-12 columns">
              <h2><%= @artist_names[i].join(',') %> on <%= DateTime.parse(j[:event_date]).strftime('%-m/%-d/%-y') %></h2>
            </div>
          </div>
        </a>

        <div class="row">
          <div class="small-12 columns">
            <%= link_to("See the Group Chat", event_group_messages_path(@user_events[i].event_id), method: :get, class: "button expanded custom") %>
          </div>

          <div class="small-12 columns">
            <%= link_to("See Who's Going", event_users_path(@user_events[i].event_id), method: :get, class: "button expanded custom") %>
          </div>
        </div>

        <hr>

      <% end %>
        
    <% end %>

<% else %>

  <div class="row">
     <div class="small-12 columns">
        You're not going to any shows.  Time to <%= link_to("change", root_path, method: :get) %> that...
    </div>
  </div>

<% end %>

app/views/user_events/show.html.erb
<div class="row">
  <div class="small-12 columns large button expanded custom">
    <h2><%= @artist_names.join(', ') %> @ <%= @event_venue['Name'] %> on <%= DateTime.parse(@event_date).strftime('%-m/%-d/%y') %></h2>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= link_to("#{@event_venue['Address']} <br> #{@event_venue['City']}, #{@event_venue['StateCode']} #{@event_venue['ZipCode']} #{image_tag("/assets/maps_icon.png", class: "gmaps")}".html_safe, @url.html_safe, method: :get, class: " left large button custom expanded") %>
  </div>
</div>

<!-- Buttons start here -->

<div class="row">
  <div class="small-12 columns">
    <%= link_to("Event Group Chat", event_group_messages_path(@event.id), method: :get, class: "left large button custom expanded") %>     
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= link_to("Find Out Who's Going", event_users_path(@event.id), method: :post, class: "left large button custom expanded") %>     
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= link_to("Buy Tickets!", @event_url, method: :post, class: "left large button custom expanded") %>     
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= link_to("Venue Website", @event_venue['Url'], method: :post, class: "left large button custom expanded") %>     
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= link_to("I Can't Go Anymore", unattend_path(params[:id]), method: :post, class: "left large button custom expanded") %>    
  </div>
</div>