config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'artist_events/:id' => "search#artist_events", as: "artist_events"
  get 'venue_events/:id' => "search#venue_events", as: "venue_events"
  get 'local_events' => "search#local_events", as: "local_events"
  get 'results' => "search#results", as: 'results'

  resources :events do 
    resources :group_messages
    resources :direct_messages
  end
  resources :user_events

  get 'user_history/:sender_id/:recipient_id' => "direct_messages#user_history", as: 'user_history'

  get 'event_dm/:event_id/:sender_id/:recipient_id' => "direct_messages#event_dm", as: 'event_dm'
  
  post 'event_dm/:event_id/:sender_id/:recipient_id' => "direct_messages#create"

  get 'my_chats/:id' => "direct_messages#my_chats", as: 'my_chats'

  get 'my_events/:id' => "user_events#my_events", as: 'my_events'

  get 'event/:id/users' => "events#event_users", as: "event_users"

  post 'attend/:id' => "user_events#attend", as: "attend"
  post 'unattend/:id' => "user_events#unattend", as: "unattend"
  
  root 'search#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Show Up" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>

  <%= display_flash_messages %>

  <nav class="top-bar" id="main_nav">
    <span class="page_header">Show Up</span>
    <div class="top-bar-right" id="prof_pic">
      <ul class="dropdown menu" data-dropdown-menu>
        <li>
          <% if user_signed_in? %>
            <%= image_tag current_user.image %>
          <% else %>
            <li><%= link_to('Login/Sign Up', new_user_session_path, method: :get, class: "button alert") %></li>
          <% end %>
            <ul class="dropdown menu" data-dropdown-menu>
              <% if user_signed_in? %>
                <li><%= link_to('My Events', user_events_path, method: :get, class: "button custom2") %></li>
                <li><%= link_to('Search', root_path, method: :get, class: "button custom2") %></li>
                <li><%= link_to('My Chats', my_chats_path(current_user.id), method: :get, class: "button custom2") %></li>
                <li><%= link_to('Logout', destroy_user_session_path, method: :delete, class: "button custom2") %></li>
              <% end %>
            </ul>
        </li>
      </ul>
    </div>
  </nav>
  
  <!-- <div class="spacer"></div> -->

  <%= yield %>
  
  <br>

  <!-- JamBase Attribution -->
  <div>Powered By:</div>
  <a href="http://www.JamBase.com" target="_top" title="JamBase Concert Search">
  <img src= "http://images.jambase.com/logos/jambase140x70.gif" alt="Search JamBase Concerts" border="0" /></a>

  </body>
</html>